### ISSUE TITLE
http2 broken ?

### ISSUE THREAD

**Issue by pabx06** [code-master5/request-http2#1]
i wanted to give this a try to compare latency for a single HTTPS request. however it didnt workout well:
```
node_modules/request-http2/request.js:707
    self.pool[poolKey] = new Agent(options)
                         ^

TypeError: Agent is not a constructor
``

**Comment by reuwi** [comment]
Got same error

**Comment by gengfire** [comment]
`
node_modules\request-http2\request.js:707
    self.pool[poolKey] = new Agent(options)
                         ^

TypeError: Agent is not a constructor
    at Request.getNewAgent (E:\jdcoupon\node_modules\request-http2\request.js:707:26)
    at Request.init (E:\jdcoupon\node_modules\request-http2\request.js:497:37)
    at new Request (E:\jdcoupon\node_modules\request-http2\request.js:131:8)
    at request (E:\jdcoupon\node_modules\request-http2\index.js:54:10)
    at Request.request [as _callback] (E:\jdcoupon\web\controller\steamController.js:274:9)
    at Request.self.callback (E:\jdcoupon\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (E:\jdcoupon\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (E:\jdcoupon\node_modules\request\request.js:1083:12)
`

**Comment by Pearyman** [comment]
Got same error
